%%
hFig = figure(1);
set(hFig, 'Position', [1200 200 1280 1024]);


%%
%%lab5 brzina vrtnje, duplo y mjerilo
t = angle_in(:,1);
%y1 = angle_in(:,2);
y2 = epsi_g(:,2);
y3 = brzina(:,2);
[AX,H1,H2] = plotyy(t,y2,t,y3,'plot');

%% za brzinu vrtnje
%set(gca, 'Xlim', [0 5], 'Ylim', [-30 30]);
%set(gca, 'linewidth', 1);
set(get(AX(2), 'children'), 'linewidth', 1.5);
set(get(AX(1), 'children'), 'linewidth', 1.5);



set(AX, 'Xlim', [0.9 1.25]);
set(AX(2), 'Ylim', [-1 10]);
set(AX(1), 'Ylim', [-3 30]);
set(get(AX(1),'Ylabel'),'String','Pozicija ( \circ)', 'fontsize', 20, 'FontName'   , 'AvantGarde') 
set(get(AX(2),'Ylabel'),'String','Brzina (rad/s)', 'fontsize', 20,'FontName'   , 'AvantGarde') 
set(get(AX(1),'Xlabel'),'String','Vrijeme (s)', 'fontsize', 20,'FontName'   , 'AvantGarde')
hLegend = legend( ...
    'Mjereni signal', 'Brzina vrtnje',  ...
    'location', 'NorthWest');



%% Ultra fancy stuff

set(get(AX(1),'Ylabel')               , ...
    'FontName'   , 'Helvetica' );

set(get(AX(2),'Ylabel')               , ...
    'FontName'   , 'Helvetica' );

set(get(AX(1),'Xlabel')               , ...
    'FontName'   , 'Helvetica' );
%set([hXLabel, hYLabel1, hYLabel2], ...
%    'FontName'   , 'AvantGarde');
set( AX             , ...
    'FontSize'   , 14           );

set( hLegend             , ...
    'FontSize'   , 18           );
%%
%set([hXLabel, hYLabel]  , ...
%    'FontSize'   , 12          );
%set( hTitle                    , ...
%    'FontSize'   , 14          , ...
%    'FontWeight' , 'bold'      );

set(AX(1), ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  ... %'YColor'      , [.3 .3 .3], ...
  'YTick'       , -30:10:30, ...
  'LineWidth'   , 1         );

set(AX(2), ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
 ... %'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:1:3, ...
  'LineWidth'   , 1         );
