%%
hFig = figure(1);
set(hFig, 'Position', [1200 200 1024 1024]);
%%
plot(Response(:,1), Response(:,2), 'b');
hold all;
plot(Response(:,1), Response(:,3), 'r');
%%
set(gca, 'Xlim', [0.75 1.5], 'Ylim', [0 700]);
%set(gca, 'linewidth', 1);
set(get(gca, 'children'), 'linewidth', 1.5);

%%
hLegend = legend( ...
    'Step', 'Odziv', ...
    'location', 'NorthWest');
%hTitle = title('Usporedba signala MultiQ-PCI kartice');
hXLabel = xlabel('Vrijeme (s)' , 'fontsize', 20);
%%
hYLabel = ylabel('Pozicija ( \circ)', 'fontsize', 20);

%% Ultra fancy stuff

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set( gca             , ...
    'FontSize'   , 14           );

set( hLegend             , ...
    'FontSize'   , 18           );
%set([hXLabel, hYLabel]  , ...
%    'FontSize'   , 12          );
%set( hTitle                    , ...
%    'FontSize'   , 14          , ...
%    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:100:800, ...
  'LineWidth'   , 1         );
