%%
plot(AnalogIn_38Hz(:,1), AnalogIn_38Hz(:,2));
hold;
stairs(AnalogOut_38Hz(:,1), AnalogOut_38Hz(:,2), 'r');
%%
plot(NaponMotor(:,1), NaponMotor(:,2));

%%
plot(Tacho(:,1), Tacho(:,2));

%%
plot(EncoderCnt(:,1), EncoderCnt(:,2));

%%
plot(EncoderRPM1(:,1), EncoderRPM1(:,2));

%%
set(gca, 'Xlim', [0 10], 'Ylim', [-80 80]);
%set(gca, 'linewidth', 1.5);
set(get(gca, 'children'), 'linewidth', 1.5, 'color', 'magenta');

%%
hLegend = legend( ...
    'Encoder RPM', ...
    'location', 'NorthEast');
%hTitle = title('Usporedba signala MultiQ-PCI kartice');
hXLabel = xlabel('Vrijeme (s)' , 'fontsize', 14);
hYLabel = ylabel('Brzina vrtnje (RPM)', 'fontsize', 14);

%% Ultra fancy stuff

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 12           );
%set([hXLabel, hYLabel]  , ...
%    'FontSize'   , 12          );
%set( hTitle                    , ...
%    'FontSize'   , 14          , ...
%    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , -80:20:80, ...
  'LineWidth'   , 1         );
